# @xml = <xmlquery.xml

POST http://www.nasdaqomxnordic.com/webproxy/DataFeedProxy.aspx
Content-Type: application/x-www-form-urlencoded

###
GET http://www.nasdaqomxnordic.com/optionsandfutures/microsite?Instrument=SSE992