name: ThetaGang CI

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  build-lambda:
    runs-on: ubuntu-latest
    environment: 
        name: ${{ github.ref_name }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            app/package-lock.json
            app/lambda/package-lock.json
      - name: Install dependencies
        run: |
          cd app
          npm ci
          cd lambda
          npm ci
      - name: Build
        run: |
          cd app/lambda
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lambda
          path: |
            app/lambda/build

  build-client:
    runs-on: ubuntu-latest
    environment: 
        name: ${{ github.ref_name }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            app/package-lock.json
            app/client/package-lock.json
      - run: |
            echo "Using baseurl: ${{ vars.API_URL }}"
      - name: Install dependencies
        run: |
          cd app
          npm ci
          cd client
          npm ci
      - name: Build
        run: |
          cd app/client
          VITE_API_URL=${{vars.API_URL}} npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: client
          path: |
            app/client/dist

  deploy:
    needs: [build-lambda, build-client]
    runs-on: ubuntu-latest
    environment: 
        name: ${{ github.ref_name }}

    permissions:
        id-token: write
        contents: read

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::700595718361:role/jogus-github-deploy-role
          aws-region: eu-north-1
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            cdk/package-lock.json
      - name: Install dependencies
        run: |
          cd cdk
          npm ci
      - name: Build
        run: |
          cd cdk
          npm run build
      - name: CDK Synth
        run: |
          cd cdk
          npx cdk synth
      - name: CDK Deploy
        run: |
          cd cdk
          npx cdk deploy ${{ vars.CDK_DEPLOY_STACK_NAME }} --require-approval never
